sebgroup/react-components

develop/components/pages/AccordionPage.tsx, src/Accordion/Accordion.tsx, src/Accordion/accordion-style.scss, src/Accordion/readme.md
This PR closes #15 
New Design:
=> feat: updated design - fixes #15

README.md
PR Summary:
- consistant to **consistent**
- chunk to **chunked**
- dependacies to **dependencies**
- future usages to **future usage**
- tested and developed to **developed and tested**
=> #update - grammar and spell checks on readme file

src/Accordion/Accordion.tsx, src/Accordion/accordion-style.scss
@DanSallau  I reviewed your pull-request and found a lot of repetitive code which is unnecessary. I did a refactoring that removes the repetitive code and added transition effect since the animation were too choppy. Please review the pull request and let me know what you think.
**57 additions** and **123 deletions**.
Please note: this pull-request is going towards your pull-request `enhancement/accordion-with-ref`. After merging this to your branch, you still need to merge your branch to `develop`
=> perf(accordion): enhanced accordion by removing repetitive code

.github/CODEOWNERS, CONTRIBUTING.md
Added guidelines on how to contribute meant for new contributors
=> docs(contributing): added guidelines for new contributors

src/Pagination/Pagination.tsx
=> feat(pagination): fix title text

src/Dropdown/Dropdown.test.tsx
removed enzyme in favour of react test utils
TODO:
=> test(dropdown): updated tests

package-lock.json, package.json
upgrades SEB bootstrap version to latest (5.1.0)
=> build(bootstrap): upgrades SEB bootstrap

package-lock.json, package.json
- Sanitize package lock
- Add sanitize to `pre-commit`
=> fix: sanitize package lock

develop/components/pages/TablePage.tsx, package-lock.json, src/Table/Table.test.tsx, src/Table/Table.tsx, src/Table/index.ts
- Fix invalid **Table** component index
- Remove invalid `async` from `describe` statement in **Table** component test
- Remove unnecessary console logs in **Table** component test
- Fix sub-dependency vulnerabilities
=> fix(table): fix invalid table component index

package-lock.json, package.json
Setting up [commitlint](https://www.google.com/search?client=safari&rls=en&q=commitlint+lci&ie=UTF-8&oe=UTF-8) to prevent non-standard commits
**IMPORTANT**: Please use `npm run commit` to submit your commits. DO NOT commit changes directly
=> Setup Commitlint

develop/components/pages/DropdownPage.tsx, src/Dropdown/Dropdown.test.tsx, src/Dropdown/Dropdown.tsx, src/Dropdown/dropdown-style.scss, src/index.json
the error message is being rendered outside the component which might cause alignment issues. also
added border color indicating an error
=> fix(dropdown): fix dropdown error rendered incorrectly

src/Table/Table.tsx
=> feat(table): fixes table sorting

.vscode/settings.json, develop/components/pages/DropdownPage.tsx, develop/components/pages/TogglePage.tsx, src/CheckBox/CheckBox.tsx, src/CheckBox/readme.md, src/Dropdown/Dropdown.test.tsx, src/Image/DivImage.test.tsx, src/Modal/Modal.test.tsx, src/Toggle/Toggle.test.tsx, src/Toggle/Toggle.tsx, src/Toggle/readme.md, src/Toggle/toggle.scss, src/Tooltip/Tooltip.test.tsx, src/index.json
toggle apis now extends the native html input element
BREAKING CHANGE: apis changed, check the documentation
=> refactor(toggle): refactor toggle apis

develop/components/pages/TablePage.tsx, src/Table/Table.test.tsx, src/Table/Table.tsx, src/Table/table-style.scss
PR 
- Removes filter by chip from table
- remove table row or td stylings, rely on bootstrap only.
=> refactor(table): remove inline table filter

src/Dropdown/Dropdown.tsx, src/index.json
only show select all option when the list consists of more than one item
=> refactor(dropdown): hide select all option if list has only one item

src/Dropdown/Dropdown.tsx
=> fix(dropdown): to show only all selected in multi mode only

package-lock.json, src/Tooltip/Tooltip.test.tsx, src/__utils/Overlay/Overlay.test.tsx, src/__utils/Overlay/Overlay.tsx, src/__utils/Overlay/placement.test.tsx, src/__utils/Overlay/placement.ts
tooltip is rendered in wrong position in long list
=> fix(tooltip): fix tooltip

public/page-data/dev-404-page/page-data.json, src/hooks/useDynamicForm.tsx, src/pages/index.tsx
=> feat(dynamic form): adds dynamic form for new docs

src/__utils/Overlay/Overlay.tsx, src/index.json
improve performance by only listening to scroll when tooltip is open
=> perf(overlay): improve performance

src/Timeline/Timeline.tsx, src/Timeline/timeline-style.scss
This fixes an issues causing a horizontal timeline to not align correctly
fixes #459 
Before:
After:
=> fix(timeline): fix horizontal timeline misalignment

develop/components/pages/ModalPage.tsx, src/Modal/Modal.test.tsx, src/Modal/Modal.tsx, src/Modal/modal.scss
=> feat(modal): add escape to dismiss and focus trap

lib/src/FeedbackIndicator/FeedbackIndicator.test.tsx, lib/src/Notification/notification-style.scss, lib/src/Tabs/Tabs.test.tsx, lib/src/Tabs/Tabs.tsx, lib/src/TextArea/TextArea.test.tsx, lib/src/Tooltip/Tooltip.test.tsx, lib/src/Tooltip/Tooltip.tsx, lib/src/index.json, src/pages/docs/buttongroup.tsx
=> fix: fix unit tests

docs/src/styles/sidemenu.scss
fixes the style for search bar in the side menu
=> docs(sidemenu): fixes search bar styles

lib/src/Dropdown/Dropdown.tsx
This PR removes conditionally added hooks based on whether it's mobile or desktop. it might not fail during
testing but it still violates react rules for hooks
=> fix(dropdown): remove conditionally added hooks

lib/src/Dropdown/Dropdown.test.tsx, lib/src/Dropdown/Dropdown.tsx
adds a way to override the label for the selcted item(s)
#547
=> feat(dropdown): adds custom lables for selected item

lib/src/Datepicker/Datepicker.tsx, lib/src/Datepicker/datepicker.scss
removes the style which make the datepicker appear invalid when the date is not valid
=> fix(datepicker): removes self null validation

lib/src/hooks/useDynamicForm.tsx
a bug fixed in should render logic to check if state even exists before checking condition
=> fix(dynamic-forms): dynamic form should render null check fix

lib/src/Datepicker/datepicker.scss
fix datepicker styles bleeding into the rest of the page by increasing specificity
fix #523
=> fix(datepicker): style specificity

docs/src/components/SideMenu.tsx
=> docs(searchbar): fix search bar style

lib/src/Modal/Modal.tsx
=> fix(modal): fix escape key listener

lib/src/Dropdown/Dropdown.test.tsx, lib/src/Dropdown/Dropdown.tsx, lib/src/hooks/useDynamicForm.tsx
=> fix(dropdown): fix dropdown select all checked by default

lib/src/Datepicker/Datepicker.test.tsx, lib/src/Datepicker/Datepicker.tsx
=> fix(datepicker): datepicker fires onchange on load

lib/src/Datepicker/Datepicker.tsx
=> fix(datepicker): fix issue where value not set if maxdate is the same date

docs/src/pages/docs/breadcrumb.tsx, lib/src/Breadcrumb/BreadcrumbItem.tsx
- remove redundant title
- improve example accessibility
=> refactor(breadcrumb): cleanup

docs/src/pages/docs/datepicker.tsx, lib/src/Datepicker/Datepicker.test.tsx, lib/src/Datepicker/Datepicker.tsx
improve date picker structure and semantics according to date picker WAI guideline [here](https://www.w3.org/TR/wai-aria-practices/examples/spinbutton/datepicker-spinbuttons.html)
- add semantic roles to custom date picker container
- add keyboard support to custom date picker day and year picker
=> refactor(datepicker): improve accessibility

lib/src/Datepicker/Datepicker.test.tsx, lib/src/Dropdown/CustomDropdownItem.test.tsx, lib/src/Dropdown/CustomDropdownItem.tsx, lib/src/Dropdown/Dropdown.test.tsx, lib/src/Dropdown/Dropdown.tsx, lib/src/Dropdown/dropdown.scss, lib/src/index.json, lib/src/utils/index.ts, lib/src/utils/keyboardHelper.test.ts, lib/src/utils/keyboardHelper.ts, lib/test/setupTests.js
improve **dropdown** structure and semantics according to WAI guidelines listed below, the `react-component` **dropdown** is a combination of both listbox and combobox design pattern hence we are referencing both guidelines:
- https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html
- https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.0pattern/combobox-autocomplete-list.html
=> refactor(dropdown): improve accessibility

docs/src/pages/docs/chip.tsx, lib/src/Chip/Chip.test.tsx, lib/src/Chip/Chip.tsx
- there is no standard guideline for `chip` component, hence the changes made are referencing from prominent component library like Material UI
- add keyboard support reference from https://mui.com/components/chips/#accessibility; when the `chip` is focused, pressing on `Backspace` or `Delete` key would trigger the on close event.
=> refactor(chip): improve accessibility

docs/src/pages/docs/timeline.tsx, lib/src/Timeline/Timeline.tsx, lib/src/Timeline/TimelineItem.test.tsx, lib/src/Timeline/TimelineItem.tsx
add tab index in timeline item
=> refactor(timeline): improve timeline accessibility

docs/src/pages/docs/steptracker.tsx, lib/src/StepTracker/StepLabel.tsx, lib/src/StepTracker/StepTracker.test.tsx, lib/src/StepTracker/StepTracker.tsx, lib/src/StepTracker/steplabel.scss, lib/src/StepTracker/steptracker.scss
- revamped step tracker to support accessibility according to this [guide ](https://a11y-guidelines.orange.com/en/web/components-examples/stepbar/)
- refactored css styles with BEM methodology
- added improvements:
- vocalization support for accessibility
- checkmark for last step if step is more than index of last step
- added accessibility example in documentation
* side note: there will be no keyboard interaction in this component but the click function of this component is retained to prevent breaking changes
re #628
=> refactor(step-tracker): refactor step tracker

docs/src/pages/docs/slider.tsx, lib/src/Slider/Slider.test.tsx, lib/src/Slider/Slider.tsx, lib/src/Slider/slider.scss
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_slider_role
*side-note: we are using div for tickmarks in this component as no browser fully supports datalist with input[type=range] yet. We also set the tickmarks and tooltip div to aria hidden as they do not play important role in screen reader.
=> refactor(slider): improve slider accessibility

docs/src/pages/docs/pagination.tsx, lib/src/Pagination/NumberedPagination.tsx, lib/src/Pagination/Page.tsx, lib/src/Pagination/Pagination.tsx
introduce new props to support pagination accessibility
https://www.a11ymatters.com/pattern/pagination/
=> refactor(pagination): improve pagination accessibility

docs/src/pages/docs/image.tsx, lib/src/Image/Img.tsx
https://www.w3.org/WAI/tutorials/images/
- add missing image role to type div image
- add accessibility improvements to image example in playground
=> refactor(img): improve accessibility

docs/src/pages/docs/notification.tsx, lib/src/Notification/Notification.tsx, lib/src/Notification/notification.scss
to only display content of notification once the animation is completed to allow sr to read out the
message
https://inclusive-components.design/notifications/
=> refactor(notification): improve accessibility

package.json
=> build(package.json): remove exports path

lib/src/SortableList/SortableList.test.tsx, lib/src/SortableList/SortableList.tsx, lib/src/SortableList/sortable-list.scss, lib/src/utils/keyboardHelper.ts
not much info related to accessibility of drag and drop so i refer to this: https://dev.opera.com/articles/accessible-drag-and-drop/
=> refactor(sortable-list): improve sortable list accessibility

lib/src/hooks/useDynamicForm.tsx
wrap some callback in usecallback hook to prevent re-renders
=> fix(dynamic-form): fix callbacks

lib/rollup.config.js
fix injectCSS is not defined bug in v7.2.1
Includes changes from 
re #756
=> fix(style-inject-bug): fix injectCSS is not defined bug

lib/rollup.config.js
fix css injection tryiong to inject at buildtime instead of runtime
=> fix(build): fix css injection

.github/CODEOWNERS, docs/src/pages/docs/textbox.tsx, lib/src/Textbox/Textbox.test.tsx, lib/src/Textbox/Textbox.tsx, lib/src/Textbox/textbox.scss
https://designlibrary.sebgroup.com/components/component-input
- add support of field instruction as per design library
=> feat: add field instruction to text box component

.github/workflows/gh-pages.yml, docs/src/components/VersionsDropdown.tsx
My previous [pull request](https://github.com/sebgroup/react-components/pull/765) did not fix the issue.
=> fix: 🐛 Bug on Switching Versions

docs/src/pages/docs/tablelist.tsx, lib/src/TableList/TableListItem.test.tsx, lib/src/TableList/TableListItem.tsx, lib/src/TableList/table-list.scss
add option to support displaying table list item in inline view
=> fix: add inline support to table list item

docs/package.json, lib/package.json, package-lock.json
update @sebgroup/frontend-tools to v2.2.1 to resolve the date comparison util issue
=> fix: date picker range validation bug

lib/src/Modal/modal.scss
- hidden visibility would disallow hidden children to be focusable
=> fix: add visibility styling to hidden modal

lib/src/Accordion/accordion.scss, lib/src/CloseButton/close-button.scss
- update focus styling for `Accordion` and `Close Button` components
- update inverted `Accordion` to match latest design library design
=> fix: focus styling
